### ISSUE TITLE
ummm

### ISSUE THREAD

**Issue by creeperplayer20** [kenygamer/VotePoints#3]
#### Versions
* PocketMine Version: Latest
* VotePoints Version: Latest Dev
* Game Version: PE / Windows 10: Win10
![Minecraft 30 03 2020 1_04_58](https://user-images.githubusercontent.com/42560781/77863444-c3f09580-7222-11ea-8fee-ee0a0be24dcc.png)

#### Configuration file

```
```

#### Crashdump or console errors

```
```

**Comment by kenygamer** [comment]
@creeperplayer20 When there are no prizes configured or the file is corrupted. Send me your `config.yml`

**Comment by creeperplayer20** [comment]
[config.zip](https://github.com/kenygamer/VotePoints/files/4409708/config.zip)

**Comment by kenygamer** [comment]
Fixed in bf5ab1e, download the latest release from [here](https://github.com/kenygamer/VotePoints)
